version: 0.2

phases:
  build:
    commands:
      - echo "Starting Maven build"
      - cd secondhand-services
      - mvn -B clean package
      - echo "Listing files in target:"
      - ls -l target

post_build:
  commands:
    - echo "Files ready for artifact upload:"
    - ls -l target/*.jar
    - echo "Current working directory:"
    - pwd
    - echo "Listing all files recursively:"
    - find .

artifacts:
  files:
    - '*.jar'
    - '*.jar.original'
  base-directory: secondhand-services/target
  discard-paths: yes
